### ISSUE TITLE
Weird spacing issue

### ISSUE THREAD

**Issue by SlightlyPeckish** [guillermo-moran/FiveIconDockXI#1]
I updatedd FiveIconDockXI and got this weird spacing issue and even if I downgrade or uninstall and reinstall the spacing issue stays the same can you help?
![image](https://user-images.githubusercontent.com/21175434/57097981-eb886680-6d10-11e9-8ec0-1facf17a6552.png)

**Comment by guillermo-moran** [comment]
Version 0.0.1 should revert the spacing issue.
I'm working on a fix!

**Comment by SlightlyPeckish** [comment]
Thank you so much that worked while I'm here where can I report bugs for eclipse? I can't seem to find it on your github

**Comment by guillermo-moran** [comment]
Fixed in 5ab6ef9303aba45497da6f3279b47ffc0752d5fb
